### PR TITLE
Fixed Timestamp from JMSTimestamp issues, Support for incorrectly typ…

### PR DESCRIPTION
**Pull request by plexaikm**
…ed WMQ Messages, Workaround for session.consume parameters bug

While porting this plugin to WebSphere MQ, encounered some issues with session.consume, perhaps some jruby-jms issues but this workaround solves the problem

### CODE REVIEW

**Comment by plexaikm** [comment]
I did sign the CLA, why the check is still failing??

**Comment by purbon** [comment]
Hi, @plexaikm CLA is properly signed, but the check only gets updated when the PR got changes, so is not aware you sign it.

**Comment by purbon** [comment]
Hi, I took a look at your code, I was wondering if you could add a test that catches this issue. Are you comfortable with it? we can provide you with directions and help for sure! just ask!.

**Comment by plexaikm** [comment]
Hi, 
Thank you for the CLA clarification, 
I tested it directly over WebSphere MQ, I will gladly add some test to it but i don't know how to test it in isolation (with no actual MQ Messages), please send me some directions

**Comment by plexaikm** [comment]
Hello, installed on another machine, this time with jruby-jms-1.2.0-java and fetched logstash-input-jms plugin, got logstash-input-jms-2.0.2-java with a bit different code than here...
Testing again and part of my changes are no longer required (the consumer workaround), how can we merge?

**Comment by plexaikm** [comment]
closing request, removing workaround and adding dependency for jruby-jms 1.2.0

**Pull request closed without merging**
